In [26]:
import torch
t=torch.load("test_mod.pth")
r=torch.load("random_inits.pth")

In [27]:
t

OrderedDict([('encoder.emb.weight',
              tensor([[ 0.0218,  0.2206, -0.1133,  ..., -0.9359, -0.1910, -0.3396],
                      [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
                      [-1.0000,  1.2193, -0.3317,  ...,  0.9588,  0.5706,  0.6785],
                      ...,
                      [-2.2977, -0.2634, -1.0889,  ..., -0.5642, -2.4436,  0.1839],
                      [ 1.8026, -2.5778,  0.0283,  ...,  0.5004, -0.7855,  1.0522],
                      [ 1.1049,  0.0935,  1.2895,  ..., -0.9364,  0.6875, -0.1765]])),
             ('encoder.rnn.weight_ih_l0',
              tensor([[-0.0307,  0.0242, -0.0162,  ...,  0.0369, -0.0241,  0.0303],
                      [-0.0182, -0.0006, -0.0047,  ..., -0.0358,  0.0273,  0.0270],
                      [-0.0098, -0.0322, -0.0277,  ..., -0.0100, -0.0253, -0.0192],
                      ...,
                      [ 0.0417,  0.0437,  0.0135,  ..., -0.0424, -0.0336, -0.0254],
                      [ 0

In [28]:
r

{'state_dict': OrderedDict([('encoder.emb.weight',
               tensor([[-1.4122, -1.0977, -0.3241,  ..., -1.0617, -0.9057,  0.7504],
                       [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
                       [-0.0861, -1.2075, -0.5092,  ..., -0.2534,  1.4067, -0.4680],
                       ...,
                       [ 0.2443, -0.1223,  0.4770,  ...,  1.2299, -0.3008,  0.0199],
                       [-0.3014,  0.2283,  2.1323,  ...,  0.2130, -2.0028,  1.1999],
                       [ 0.1649,  0.7938,  0.1125,  ..., -0.2407,  2.1255,  2.5534]])),
              ('encoder.rnn.weight_ih_l0',
               tensor([[ 0.0196,  0.0243,  0.0403,  ...,  0.0137,  0.0028,  0.0293],
                       [ 0.0238,  0.0370,  0.0037,  ..., -0.0137, -0.0159,  0.0390],
                       [-0.0008, -0.0409,  0.0283,  ...,  0.0300,  0.0154,  0.0265],
                       ...,
                       [-0.0261, -0.0066,  0.0388,  ..., -0.0173, -0.0287, -0.0149