In [15]:
import torch
head_z = torch.randn((1,4,1)).squeeze()
if head_z is not None:
    # head_z is over KV heads, need to expand to query heads
    #head_z_expanded = head_z.repeat_interleave(self.num_key_value_groups)
    head_z_expanded = head_z.repeat_interleave(4)
    attn_output = attn_output * head_z_expanded.view(1, -1, 1, 1)

In [19]:
head_z_expanded.view(1, -1, 1, 1)

tensor([[[[-0.0166]],

         [[-0.0166]],

         [[-0.0166]],

         [[-0.0166]],

         [[ 0.2027]],

         [[ 0.2027]],

         [[ 0.2027]],

         [[ 0.2027]],

         [[ 1.0439]],

         [[ 1.0439]],

         [[ 1.0439]],

         [[ 1.0439]],

         [[-1.0207]],

         [[-1.0207]],

         [[-1.0207]],

         [[-1.0207]]]])

In [9]:
head_z

tensor([ 0.2738, -0.1254,  0.5654,  0.5953])

In [38]:
x=torch.randn(1, 2, 3, 4) 
o=2*torch.ones(1,2,1,1)

In [39]:
x.shape

torch.Size([1, 2, 3, 4])

In [44]:
(x*o)

tensor([[[[-0.7287, -0.2093, -0.2381,  1.5861],
          [-0.4143,  1.3098,  0.8429,  0.5061],
          [ 3.1970,  0.5262,  0.3747, -1.8900]],

         [[-0.9846,  0.1322,  0.5896,  3.8598],
          [ 0.5506, -0.6531, -1.5631, -0.0937],
          [ 0.2767,  0.0053, -2.0557, -1.1528]]]])

In [45]:
x

tensor([[[[-0.3644, -0.1047, -0.1191,  0.7930],
          [-0.2072,  0.6549,  0.4214,  0.2530],
          [ 1.5985,  0.2631,  0.1874, -0.9450]],

         [[-0.4923,  0.0661,  0.2948,  1.9299],
          [ 0.2753, -0.3266, -0.7815, -0.0468],
          [ 0.1383,  0.0027, -1.0279, -0.5764]]]])