In [1]:
import torch
x = torch.tensor([1, 2, 3])
x.repeat_interleave(2)

tensor([1, 1, 2, 2, 3, 3])

In [65]:
x = torch.ones((1,4,1,1))
x[0][0][0]=0
newx=x.repeat_interleave(8,dim=1)

In [66]:
x

tensor([[[[0.]],

         [[1.]],

         [[1.]],

         [[1.]]]])

In [77]:
torch.randn((22,)).* torch.randn((22,4)) 

RuntimeError: outer: Expected 1-D argument vec2, but got 2-D

In [72]:
l0m llama 337 all_head_score: torch.Size([22, 1, 1]) head_score:  torch.Size([22, 4, 1]) hidden_score torch.Size([2048])
l0m llama 337 all_head_score: torch.Size([22, 1, 1]) head_score:  torch.Size([22, 4, 1]) hidden_score torch.Size([2048])
l0m llama 337 all_head_score: torch.Size([22, 1, 1]) head_score:  torch.Size([22, 4, 1]) hidden_score torch.Size([2048])
l0m llama 337 all_head_score: torch.Size([22, 1, 1]) head_score:  torch.Size([22, 4, 1]) hidden_score torch.Size([2048])


tensor([[[ 0.0000e+00,  0.0000e+00, -0.0000e+00,  ..., -0.0000e+00,
           0.0000e+00, -0.0000e+00],
         [ 0.0000e+00,  0.0000e+00, -0.0000e+00,  ..., -0.0000e+00,
          -0.0000e+00,  0.0000e+00],
         [ 0.0000e+00, -0.0000e+00,  0.0000e+00,  ..., -0.0000e+00,
           0.0000e+00,  0.0000e+00],
         ...,
         [-0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -0.0000e+00,
          -0.0000e+00,  0.0000e+00],
         [ 0.0000e+00, -0.0000e+00,  0.0000e+00,  ..., -0.0000e+00,
           0.0000e+00,  0.0000e+00],
         [-0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          -0.0000e+00, -0.0000e+00]],

        [[-2.2615e+00, -8.9886e-02,  1.3704e+00,  ...,  1.9570e+00,
          -2.0834e-01, -1.0033e+00],
         [-7.9784e-02,  7.6110e-01,  9.8536e-01,  ...,  5.0254e-01,
          -4.8062e-01, -4.7191e-01],
         [ 1.6890e+00,  8.4645e-01, -8.0029e-01,  ...,  7.3432e-02,
          -4.1808e-01,  4.6212e-01],
         ...,
         [-1.9425e+00, -9

In [69]:
(ran*newx).shape

torch.Size([1, 32, 30, 64])